apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-liveness
spec:
  containers:
  - name: container-nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 80
