apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  replicas: 3
  selector:
    app: webui
 template:
   metadata:
     name: pod-nginx
     labels:
       app: webui
   spec:
     containers:
     - name: container-nginx
       image: nginx:latest
