apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  replicas: 3
  selector:
    env: dev
  template:
    metadata:
      name: pod-nginx
      labels:
        env: dev
    spec:
      containers:
      - name: container-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
