# echo -n "test" | base64 > dGVzdA==
# echo -n "demo" | base64 > ZGVtbw==

apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: default
type: Opaque
data:
  MYSQL_USER: ZGVtbw==
  MYSQL_ROOT_PASSWORD: dGVzdA==
  MYSQL_PASSWORD: dGVzdA==
